language: ruby
rvm: 2.6
install: bundle install
before_script:
- git config --global user.email "malecki.maciej@gmail.com"
- git config --global user.name "Maciej Malecki"
- git remote rm origin
- git remote add origin https://maciejmalecki:${GH_TOKEN}@github.com/maciejmalecki/jekyll-starter.git
script: JEKYLL_ENV=production bundle exec rake site:deploy
env:
  global:
    secure: npdLrTuc/l4TiFX+z0uOtijeIid8+nxQEftkOzleWBDj/RISu8knCjBH3ocEU/ml4ZrE/fU2yqG4B5/MF7UA/KHYxr74P62VRUzKuo6H0Q/cFfw3HO9kBcV3IutIUTFZPTRtYBhpErUlutAAYXqulBdRqb6Xyg9DMN9exNaUNSkFAYDRpU+Dtch3JaffeH+nMF/J7M7O+CDCyvq69gt8h4rUDmkeqGhq3txBlGp7Zxx22o+CkTaj8IUlKRiZhYHdEkMdP90Re+qq4PV637O1S4lSf4JF/IVHypFqi04baeLLRJu6eIjQIHJDdy7W3a2MVLiG5RHD59TdMXOxqjXzRlo/sGl2lIIU5i9zyjFTsNYcEpcbMXIETXjOmZwqEevYToLn1yni2539Vmi799mDpmkJvXcBWZjtMpjMUte1W0Kvx0HSLgOFOYkUjuJF4ZgL32HoUZPBgyGMdkuKKt6EBCP/kdkQ/R46Dbfh4uzRf583o5GpYjmV8JtcrvSN6iCpgUBFvMdyclfYDTbagZT+lLoOo/GEo7ie+4n7HIhzBnOxcxkEKYK2iC2Oh437SdN3SW+jo7eyTlBatpV5SDe+076PHcLuP7ZJnqWDcYfbuATDIyCgtODR5LURjea1nAooH+PQjeMGDx3ysxdk3XaMtvomPKmFKCG3GfyfyayyHnY=
