language: ruby
rvm: 2.6
install: bundle install
before_script:
- git config --global user.email "malecki.maciej@gmail.com"
- git config --global user.name "Maciej Malecki"
- git remote rm origin
- git remote add origin https://maciejmalecki:${GH_TOKEN}@github.com/maciejmalecki/jekyll-starter.git
script: JEKYLL_ENV=production bundle exec rake site:deploy
env:
  global:
    secure: V7/UHww4lksnIyHuv7owNjznX3BMGwC4fpBSDGzRPwXS3wG0d91JbtMPA1tpvb/r/Xd4Jrf+ubwMhQEOpPkAfQj7C2d+0oF7F1xs8jgwOXsCp0f2z771nAJ0Jf4PPvpusNB+Ha9bo0VHTiSZ6dwZJXDBdClBt394/0JpshkNsSjTirMdPzeOT1pw7gIBsjzlppsZl0uTGtJcM6v7KmuB7OnnvnuwgkEe8NwMvmisEoNcs7yRy1ObpLLxdia7pwm0nq36u+nwgaDkDDTbUoMDbsDKv4S50jGhxsw1rENzd0mGKbgejK86XBTb1oy2IDFiSUVbyHZy8Mg33WmN6fg0UUqqeC0TYthdGkfLc+/I7gPxrmHHQ95x5bXKlEElVAaY7tXguZOJcRXGrqcuLMgfs3ZKFtO4nCdHg9qOqymez/7MbYwngUmcpg85VwEMrcecaOvuWfBnFqKX/kjlBI09Y8yZpI0ZrBvDKR3aRh2UjEX2cvepYVL1mXFuF/nmiY9lTI2T8FEhlHX+qBGjg6shfiQMJlWT9XPaiwmZKPOSKfJQvv6DLdOWYpn1WQQm7Q1DQkGZFsqnMsMlPSDZ8Im7qUs/Mw1jbrFCQc7LALassWgmfBIbwIV7X4GwGEqPAa4HQI1Ll5Y8Y3wEHi07HrTsx+9lGGGiklm+H8mqybrBT7Q=
